version: '3'

services:
  postgres:
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD=password
      - PGPASSWORD=password
  redis:
    image: redis:alpine
  nginx:
    build:
      context: nginx
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - 3050:80
  api:
    image: node:alpine
    working_dir: /app
    volumes:
      - ./server:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGPOST=5432
      - PGDATABASE=postgres
      - PGPASSWORD=password
    command: npm run dev -- -L
  worker:
    image: node:alpine
    working_dir: /app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - ./worker:/app
    command: npm run dev -- -L # -L: enable polling to watch for changes
  client:
    image: node:alpine
    working_dir: /app
    stdin_open: true # important for react-scripts run
    environment:
      - CHOKIDAR_USEPOLLING=true # enable polling to watch for changes
    volumes:
      - ./client:/app
    command: ["npm", "run", "start"]
